# Generated by Django 4.2.16 on 2024-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца действия кода'),
        ),
    ]
