# Generated by Django 4.2.16 on 2024-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codes_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='live_days',
            field=models.PositiveIntegerField(verbose_name='Срок действия кода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='E-mail'),
        ),
    ]
